language: go

go:
  - 1.7
  - master
  - tip

env:
  - SERVER_APP=waffle-server CLIENT_APP=waffle-client

cache:
  directories:
    - $SERVER_APP/vendor

install:
  - echo "TRAVIS_INSTALL"
  - echo $PWD

script:
  - cd $SERVER_APP && make && cd $TRAVIS_BUILD_DIR
