language: go

go:
  - 1.7
  - master
  - tip

env:
  - SERVER_APP=waffle-server CLIENT_APP=waffle-client

cache:
  directories:
    - $SERVER_APP/vendor

install:
  - cd $SERVER_APP &&
    make install &&
    make build-all &&
    cd $TRAVIS_BUILD_DIR

script:
  - cd $SERVER_APP && make build && cd $TRAVIS_BUILD_DIR
